#!/snap/rocketchat/current/python/bin/python

from os.path import join
import os, sys
sys.path.append(join(os.environ['SNAP'], 'hooks'))

from rocketchat_hooks import RocketChatInstaller

RocketChatInstaller().install()