#!/snap/rocketchat/current/python/bin/python

import os, sys
sys.path.append(os.path.join(os.environ['SNAP'], 'hooks'))

from rocketchat_hooks import RocketChatInstaller

RocketChatInstaller().install()
